[package]
name = "rusty_client"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = { version = "0.29.0", default-features = false, features = ["derive-more", "event-stream"]}
ratatui = "0.29.0"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
